services:
  fe-tracker:
    image: ghcr.io/vrail3/fe-tracker:latest
    container_name: fe-tracker
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      NVIDIA_PRODUCT_URL: "https://marketplace.nvidia.com/de-de/consumer/graphics-cards/nvidia-geforce-rtx-5080/"
      STOCK_CHECK_INTERVAL: "1000"
      SKU_CHECK_INTERVAL: "10000"
      NTFY_TOPIC: "example_topic"
      TIMEZONE: "Europe/Berlin"