name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*']
    paths:
      - '**.go'
      - '**.html'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [main]

jobs:
  docker:
    name: Build and push FE-Tracker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/fe-tracker
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=docker-build-${{ github.ref_name }}
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/fe-tracker:latest
          cache-to: |
            type=gha,mode=max,scope=docker-build-${{ github.ref_name }}
            type=inline

      - name: Delete old images
        if: github.event_name != 'pull_request'
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'fe-tracker'
          package-type: 'container'
          min-versions-to-keep: 1
          token: ${{ secrets.GITHUB_TOKEN }}