name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*']
    paths:
      - '**.go'
      - 'go.*'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
      - 'templates/status.html'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'go.*'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
      - 'templates/status.html'

jobs:
  docker:
    name: Build and push FE-Tracker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            image=moby/buildkit:v0.12.5
            network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/fe-tracker
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optimize cache configuration
          cache-from: |
            type=gha,scope=${{ github.workflow }}
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/fe-tracker:main
          cache-to: type=gha,mode=min,scope=${{ github.workflow }}
          # Add build optimization flags
          provenance: false
          build-args: |
            BUILDKIT_STEP_LOG_MAX_SIZE=10485760
            DOCKER_BUILDKIT=1
            BUILDKIT_PROGRESS=plain
            COMPOSE_DOCKER_CLI_BUILD=1
          # Add output configuration
          outputs: type=image,compression=zstd